---
# Location where configuration files will be stored.
config_dir: '~/dev/pi-dash/internet-pi-conf'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'home.local'
domain_pihole: 'pihole'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local

# Pi-hole configuration.
pihole_enable: false
pihole_hostname: pihole
pihole_timezone: Asia/Ho_Chi_Minh
pihole_password: "659142"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "Boyluu96@"
monitoring_speedtest_interval: 120m
monitoring_ping_interval: 120s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - https://google.com/;google.com
  - https://github.com/;github.com
  - https://duckdns.org;duckdns
  - https://apple.com/;apple.com
  - https://ken-nas.duckdns.org;nas-omv
  - https://ld.ken-nas.duckdns.org;ld
  - https://nginx.ken-nas.duckdns.org;nginx-nas

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
prometheus_tsdb_retention_time: 60d

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
